# Generated by Django 5.0.7 on 2024-07-29 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AurochTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleName', models.CharField(max_length=255)),
                ('referenceSequence', models.CharField(choices=[('All', 'All'), ('Human', 'Human'), ('Ecoli', 'Ecoli'), ('Hpv', 'Hpv'), ('Lambda', 'Lambda'), ('Bacteria', '细菌'), ('Custom', '用户指定本地文件')], max_length=255)),
                ('fastqFile', models.CharField(max_length=255)),
                ('filter', models.BooleanField(default=False)),
                ('generateConsensus', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobAuroch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('arg1', models.CharField(max_length=128, verbose_name='样本名称')),
                ('arg2', models.IntegerField(choices=[(1, 'Human-hg38'), (2, 'Human-hg19'), (3, 'Mouse-mm10'), (4, 'HIV'), (5, 'Ecoli')], default=1, verbose_name='参考样本')),
                ('arg3', models.CharField(max_length=128, verbose_name='Fastq文件')),
                ('arg4', models.IntegerField(choices=[(1, 'True'), (2, 'False')], default=1, verbose_name='是否过滤')),
                ('arg5', models.IntegerField(choices=[(1, 'True'), (2, 'False')], default=2, verbose_name='是否生成一致性序列')),
            ],
            options={
                'verbose_name': 'JobAuroch',
                'verbose_name_plural': 'JobAuroch_plural',
                'db_table': 'JobAuroch_db',
            },
        ),
        migrations.CreateModel(
            name='JobUniversal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('workfolw', models.CharField(max_length=128, verbose_name='分析流程')),
                ('parameters', models.JSONField(verbose_name='任务参数')),
                ('sampleName', models.CharField(max_length=128, verbose_name='样本名称')),
                ('projectName', models.CharField(max_length=128, verbose_name='项目名称')),
                ('userName', models.CharField(max_length=128, verbose_name='用户名称')),
                ('workDir', models.CharField(max_length=128, verbose_name='工作目录')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JobUniversal',
                'verbose_name_plural': 'JobUniversal',
                'db_table': 'JobUniversal',
            },
        ),
        migrations.CreateModel(
            name='meiliUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('account', models.CharField(max_length=128, verbose_name='账户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
            options={
                'verbose_name': 'meiliUser',
                'verbose_name_plural': 'meiliUser',
                'db_table': 'meiliUser',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(default='', max_length=22, verbose_name='名称')),
                ('number', models.IntegerField(default=0, verbose_name='座位数量')),
                ('photo', models.FileField(default='', upload_to='Room/photo/', verbose_name='头像')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
            ],
            options={
                'verbose_name_plural': '自习室管理',
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='SignCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('text', models.TextField(default='', verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
            ],
            options={
                'verbose_name_plural': '签到码',
                'db_table': 'sign_code',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(default='', max_length=22, verbose_name='姓名123')),
                ('password', models.CharField(default='', max_length=32, verbose_name='密码')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('email', models.CharField(default='', max_length=22, verbose_name='邮箱1')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('photo', models.FileField(default='', upload_to='Students/photo/', verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
            ],
            options={
                'verbose_name_plural': '学生管理',
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(default='', max_length=120, verbose_name='题目')),
                ('text', models.TextField(default='', verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
            ],
            options={
                'verbose_name_plural': '提示管理',
                'db_table': 'Text',
            },
        ),
        migrations.CreateModel(
            name='Integrals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(default='', max_length=220, verbose_name='警告题目')),
                ('text', models.TextField(default='', max_length=220, verbose_name='警告内容内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.students', verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '扣积分管理',
                'db_table': 'Integral',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('number', models.IntegerField(default=0, verbose_name='预约座位号')),
                ('period', models.IntegerField(choices=[(1, '上午'), (2, '下午'), (3, '晚自习')], default=1, verbose_name='时间')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.IntegerField(choices=[(1, '预约'), (2, '已签到'), (3, '未签到'), (4, '已取消')], default=1, verbose_name='活跃状态')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.rooms', verbose_name='自习室')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.students', verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '预约管理',
                'db_table': 'Booking',
            },
        ),
    ]
