"""
Django settings for AurochOnline project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dsvds%4jzg1w9^k4k20+yd3zd5c07h(&6%ms+e1-8-ul^t!7ly'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'login',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'login.SimpleMiddleware.SimpleMiddleware',
]

ROOT_URLCONF = 'AurochOnline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AurochOnline.wsgi.application'



# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, "assets")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLEUI_LOGO = '/static/img/logo.svg'



# simpleui 排序后台app导航栏
SIMPLEUI_DEFAULT_THEME = 'e-green.css'

SIMPLEUI_CONFIG = {
    'system_keep': True,
    'menu_display': ['开始分析','MeMob96仪器开发','任务管理','用户管理'],
    'dynamic': True,
    'menus': [
    {
        'name': '开始分析',
        'models': [
        {
            'name': 'Auroch分析',
            'url': '/login/submit_auroch/'
        },{
            'name': '新冠全基因组分析',
            'url': '/login/submit_covid/'
        },{
            'name': '致病菌分析',
            'url': '/login/empty/'
        },
        {
            'name': '新冠污水分析',
            'url': '/login/submit_sewage_water/'
        },{
            'name': '广谱病原微生物分析',
            'url': '/login/submit_mapping/'
        },
        {
            'name': '测试页面',
            'url': '/login/test1/'
        }]
    },{
        'name': 'MeMob96仪器开发',
        'models': [
            {
            'name': '训练数据采集',
            'url': '/login/submit_pod5_plotter/'
        },{
            'name': '丢数据Log文件解析',
            'url': '/login/submit_handle_log/'
        }]
    },{
        'name': '任务管理',
        'models': [
        {
            'name': '任务管理',
            'url': '/login/view_job/'
        }]
    },{
        'name': '用户管理',
        'models': [{
            'name': '用户管理',
            'url': '/admin/login/meiliuser/'
        },{
            'name': '日志管理',
            'url': '/admin/login/jobuniversal/'
        }]
    }]
}

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_THEME = 'simpleui-x'
SIMPLEUI_LOGO = '/static/img/logo_white.png'


CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

#Absolute Path
DIR = '/home/nanopore/01.Workdir/01.NAS/test'
POD5_BIN_PATH = '/home/nanopore/02.Software/mc.3/envs/python312/bin/pod5'
PYTHON_BIN = '/home/nanopore/02.Software/mc.3/envs/python312/bin/python'
PY38_PYTHON = '/home/nanopore/02.Software/mc.3/envs/py38/bin/python'
#Relative Path
MAINDIR = f'{DIR}/'
DATADIR = f'{DIR}/DATADIR/'
WORKDIR = f'{DIR}/WORKDIR/'
SCRIPTDIR = f'{DIR}/SCRIPT/'
POD5_PLOTER_PATH = f'{SCRIPTDIR}/pod5_plotter/pod5_ploter_report.py'
COVID19_PATH = f'{SCRIPTDIR}/covid/Covid19/bin/Covid19_pipline.py'
META_GENOMIC_PATH = f'{SCRIPTDIR}/meta/Meta_genomics/bin/Meta_pipline.py'
HANDLE_LOG_PATH = f'{SCRIPTDIR}/handle_log/handle_log.py'
AUROCH_TEST_INFO_PATH=f'{SCRIPTDIR}/auroch/auroch_v0.6/lib/testInfo.txt'
AUROCH_BIN_PATH=f'{SCRIPTDIR}/auroch/auroch_v0.6/auroch_v0.6.sh'
AUROCH_MODEL = f'{SCRIPTDIR}/auroch/model'

#Dict
AUROCH_REF_DICT={'Covid':f'{SCRIPTDIR}/auroch/ref/covid-19.fasta',
                 'Lambda':f'{SCRIPTDIR}/auroch/ref/lambda.fasta',
                 'Human':f'{SCRIPTDIR}/auroch/ref/GRCh38_latest_genomic.fna',
                 'Ecoli':f'{SCRIPTDIR}/auroch/ref/coli.fasta',
                 'HPV':f'{SCRIPTDIR}/auroch/ref/HPA.fa'}
AUROCH_MODEL_DICT={'20240821.5':'MeMob新冠模型',
                   '20240930.2':'MeMob通用模型',}

